// PRODUCT ACTION TYPES
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FIND_PRODUCT = 'FIND_PRODUCT';
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
export const FAIL_LOADING_PRODUCTS = 'FAIL_LOADING_PRODUCTS';
